# Generated by Django 4.2 on 2024-03-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amir',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
