# Generated by Django 4.2 on 2024-04-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_amir_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, null=True)),
                ('last_name', models.CharField(blank=True, null=True)),
                ('ewq', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Amin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TEST_VIEW',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, null=True)),
                ('lname', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ama',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, null=True)),
                ('lname', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'a',
            },
        ),
        migrations.RenameModel(
            old_name='Amir',
            new_name='Todo',
        ),
    ]
