# Generated by Django 4.2 on 2024-04-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_amin_test_view_a_rename_amir_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, null=True)),
                ('lname', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'b',
            },
        ),
    ]
