# Generated by Django 4.2 on 2024-04-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, null=True)),
                ('lname', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'd',
            },
        ),
    ]
