# Generated by Django 4.2 on 2024-04-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_delete_test_view_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
