# Generated by Django 4.2 on 2024-04-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='first_name',
            new_name='F_name',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='last_name',
            new_name='L_name',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='father_name',
        ),
    ]
